export const MENU_INFO = 'INFO';
export const MENU_SEO = 'SEO';
export const MENU_CONTACT = 'CONTACT';

export const ACTION_SET_INFO = 'SET_INFO';
export const ACTION_SET_SEO = 'SET_SEO';
export const ACTION_SET_CONTACT = 'SET_CONTACT';

// SEO 查询
export const SEO_REQUEST = 'SEO_REQUEST'
export const SEO_SUCCESS = 'SEO_SUCCESS'
export const SEO_FAILURE = 'SEO_FAILURE'

// SEO 更新
export const SEO_UPDATE_REQUEST = 'SEO_UPDATE_REQUEST'
export const SEO_UPDATE_SUCCESS = 'SEO_UPDATE_SUCCESS'
export const SEO_UPDATE_FAILURE = 'SEO_UPDATE_FAILURE'


//SITE 
export const SITE_LOAD = 'SITE_LOAD'
export const SITE_UPDATE_TITLE = 'SITE_UPDATE_TITLE'
export const SITE_CREATE_DOMAIN = 'SITE_CREATE_DOMAIN'
export const SITE_DELETE_DOMAIN = 'SITE_DELETE_DOMAIN'
export const SITE_UPDATE_FACTOR = 'SITE_UPDATE_FACTOR'
export const SITE_UPDATE_EMAIL = 'SITE_UPDATE_EMAIL'