
// 产品列表
// 新建产品
export const PRODUCT_LIST_LOAD_SUCCESS = 'PRODUCT_LIST_LOAD_SUCCESS'
// 删除产品
export const PRODUCT_LIST_DELETE_SUCCESS = 'PRODUCT_LIST_DELETE_SUCCESS'
// 置顶产品
export const PRODUCT_LIST_TOP_SUCCESS = 'PRODUCT_LIST_TOP_SUCCESS'
// 取消置顶产品
export const PRODUCT_LIST_UNTOP_SUCCESS = 'PRODUCT_LIST_UNTOP_SUCCESS'
// 批量删除产品
export const PRODUCT_LIST_DELETE_MANY_SUCCESS = 'PRODUCT_LIST_DELETE_MANY_SUCCESS'
// 全部删除产品
export const PRODUCT_LIST_DELETE_ALL_SUCCESS = 'PRODUCT_LIST_DELETE_ALL_SUCCESS'



// 产品
// 新建产品
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
// 加载产品
export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS'
// 提交产品
export const PRODUCT_SUBMIT_SUCCESS = 'PRODUCT_SUBMIT_SUCCESS'
// 产品属性
export const PRODUCT_UPDATE_OPTIONS = 'PRODUCT_UPDATE_OPTIONS'
// 产品属性
export const PRODUCT_BEFORE_OPTIONS = 'PRODUCT_BEFORE_OPTIONS'




// 加载产品系统信息
export const PRODUCT_SYSTEM_LOAD_SUCCESS = 'PRODUCT_SYSTEM_LOAD_SUCCESS'




// 多系统页面
// 加载多系统信息
export const SYSTEMS_LOAD_SUCCESS = 'SYSTEMS_LOAD_SUCCESS'
// 删除系统
export const SYSTEMS_DELETE_SUCCESS = 'SYSTEMS_DELETE_SUCCESS'
// 新增系统
export const SYSTEMS_CREATE_SUCCESS = 'SYSTEMS_CREATE_SUCCESS'

// 单系统
// 加载多系统信息
export const SYSTEM_LOAD_SUCCESS = 'SYSTEM_LOAD_SUCCESS'
// 提交系统信息
export const SYSTEM_SUBMIT_SUCCESS = 'SYSTEM_SUBMIT_SUCCESS'


//分类
//加载分类Categories
export const CATEGORIES_PRODUCT_LOAD_SUCCESS = 'CATEGORIES_PRODUCT_LOAD_SUCCESS'
//加载分类Categories
export const CATEGORIES_LOAD_SUCCESS = 'CATEGORIES_LOAD_SUCCESS'
//提交分类Categories
export const CATEGORIES_UPDATE_SUCCESS = 'CATEGORIES_UPDATE_SUCCESS'
//删除分类Categories
export const CATEGORIES_DELETE_SUCCESS = 'CATEGORIES_DELETE_SUCCESS'


// 控制器
// 进入系统
export const CTL_SYSTEM_CHANGE = 'CTL_SYSTEM_CHANGE'
// 返回多系统
export const CTL_SYSTEM_BACK = 'CTL_SYSTEM_BACK'
// 按钮切换
export const CTL_MENUS_CHANGE = 'CTL_MENUS_CHANGE'
// 切换编辑
export const CTL_EDIT_CHANGE = 'CTL_EDIT_CHANGE'
// 加载完成
export const CTL_LOAD_COMPLETED = 'CTL_LOAD_COMPLETED'
// 切换编辑分类
export const CTL_EDIT_CATEGORY = 'CTL_EDIT_CATEGORY'
// 关闭编辑分类
export const CTL_CLOSE_CATEGORY = 'CTL_CLOSE_CATEGORY'

